- hosts: localhost
  tasks:
    - name: Updating all packages
      apt:
        name: '*'
        state: latest
      become: true
    - name: Remove Shotwell
      become: yes
      package:
        name: shotwell
        state: absent
    - name: Basic Packages
      apt:
        name: [ "snap", "openssh-server", "htop", "nmap", "rsyslog", "zsh", "speedtest-cli", "rdesktop" , "smartmontools", "gthumb" , "dirmngr", "apt-transport-https", "curl", "gnupg2", "nmon", "sysstat", "iptraf-ng", "jq", "iotop", "wget", "git", "dos2unix" ]
        state: latest
      become: true
