- hosts: localhost
  tasks:
  - name: Copying Hipchat repos
    copy:
      src: templates/hipchat4.repo 
      dest: /etc/apt.repos.d/hipchat4.repo
      owner: root
      group: root
      mode: 0644
    become: true
  - name: Copying dropbox repos
    copy:
      src: templates/dropbox.repo 
      dest: /etc/apt.repos.d/dropbox.repo
      owner: root
      group: root
      mode: 0644
    become: true
  - name: Copying google-chrome repos
    copy:
      src: templates/google-chrome.repo 
      dest: /etc/apt.repos.d/google-chrome.repo
      owner: root
      group: root
      mode: 0644
    become: true
  - name: Copying dropbox repos
    copy:
      src: templates/vscode.repo 
      dest: /etc/apt.repos.d/vscode.repo
      owner: root
      group: root
      mode: 0644
    become: true 
  - name: Updating all packages
    apt:
      name: '*'
      state: latest
    become: true
  - name: Basic Packages
    apt:
      name: [ "hipchat4", "nautilus-dropbox", "code", "google-chrome-stable", "terminator", "vim" ]
      state: latest
    become: true
  - name: Enable Flathub repository
    become: yes
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - name: Install Slack
    command: flatpak install --assumeyes flathub com.slack.Slack
    become: yes
  - name: Install Skype
    command: flatpak install --assumeyes flathub com.skype.Client
    become: yes
  - name: Install Spotify
    become: yes
    command: flatpak install --assumeyes flathub com.spotify.Client
  - name: Install VLC
    command: flatpak install --assumeyes flathub org.videolan.VLC
    become: yes
  - name: Install Draw.io
    command: flatpak install --assumeyes flathub com.jgraph.drawio.desktop
    become: yes
  - name: Install Postman
    command: flatpak install --assumeyes flathub com.getpostman.Postman
    become: yes 
  - name: Install Regexp Checker
    command: flatpak install --assumeyes flathub com.github.artemanufrij.regextester   
    become: yes
  - name: Install PyCharm IDE
    command: flatpak install --assumeyes flathub com.jetbrains.PyCharm-Community  
    become: yes
  - name: Install GIMP
    command: flatpak install --assumeyes flathub org.gimp.GIMP  
    become: yes
